from . import task
from . import rsync
from . import proc_beh
from . import GLM
from .analyses import test_periodicity
from .plot import plot_activity_on_graph
from .load import load_data
from .utils import align_activity
from .SVD_analysis import variance_explained_U,variance_explained_V,variance_explained_both,get_mean_activity_matrix
from . import open_field_analysis